user_controllers:
  resource: '../src/CenaConDelitto/UserArea/Controller'
  type: attribute

login_controllers:
  resource: '../src/CenaConDelitto/Login/Controller'
  type: attribute

app_logout:
  path: /logout
  methods: GET
