homepage:
    path: /
    controller: App\CenaConDelitto\UserArea\Controller\HomeController::homepage
test:
    path: test/
    controller: App\CenaConDelitto\UserArea\Controller\HomeController::test
